functional:
  - Пользователь должен иметь возможность зарегестрироваться на сайте.
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность выбрать задачу при создании игры.
  - Пользователь должен иметь возможность выбрать соперника.
  - Пользователь должен видеть код соперника в режиме онлайн.
  - Пользователь видит свой редактор и соперника.
  - Пользователь должен иметь возможность проверить свое решение неограниченное количество раз.
  - Пользователь должен иметь возможность войти в личный кабинет.
  - Пользователь должен иметь возможность просматривать свой рейтинг.
  - Пользователь должен иметь возможность пригласить в игру соперника по ссылке.

non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
