functional:
  - Пользователь должен иметь возможность зарегестрироваться на сайте.
  - Пользователь должен иметь возможность авторизоваться на сайте.
  - Пользователь должен иметь возможность авторизоваться через Github.
  - Пользователь должен иметь возможность выбрать задачу при создании игры.
  - Пользователь должен иметь возможность выбрать соперника.
  - Пользователь должен видеть код соперника в режиме онлайн.
  - Пользователь должен иметь возможность выбрать язык программирования.
  - Пользователь видит свой редактор и соперника.
  - Пользователь должен иметь возможность проверить свое решение неограниченное количество раз.
  - Пользователь должен иметь возможность войти в личный кабинет, просмотреть и отредактировать информацию.
  - Пользователь должен иметь возможность просматривать свой рейтинг.
  - Пользователь должен иметь возможность пригласить в игру соперника по ссылке.
  - Пользователь может выбирать и менять во время игры язык программирования.
  - Пользователь должен иметь возможность выбрать уровень сложности игры.
  - Пользователю доступна запись игры после ее завершения.
  - Зарегестрированному пользователю доступен чат.
  - 

non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Задачи на сайте доступны на двух языках - русском и английском.

implicit:
  - Зарегестрированный пользователь видит список онлайн игроков.
  - На главной странице авторизованным пользователям выводится список лидеров, рейтинг.
  - Игрок не может менять код соперника.
  
